name: Run Azure OCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-azure-ocr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run OCR script
      env:
        AZURE_SUBSCRIPTION_KEY: ${{ secrets.AZURE_SUBSCRIPTION_KEY }}
        AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
      run: |
        python src/azure_ocr.py
